@startuml
'https://plantuml.com/class-diagram

class NameSorter
class readNames{
    input: Scanner
}

class outputNames{
    names: ArrayList
}

class main{
    args: String[]
}

NameSorter <|-- readNames
NameSorter <|-- outputNames
NameSorter <|-- main

@enduml